export type {
  Student,
  Lesson,
  LessonType,
  LessonStatus,
  LessonRecord,
  Homework,
  HomeworkStatus,
  PracticeSection,
  SectionStatus,
  Recording,
  BillingRecord,
  BillingType,
  IpcResponse,
  MonthlyStats,
  BillingSummary,
  StudentStats,
  WindowApi,
} from '@shared/types';
